require("core.options")
require("core.keymaps")
require("plugins.plugins-setup")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.mason")
require("plugins.nvim-cmp")
require("plugins.mul-cursors")
