# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FDF5E4
background         #17160E
cursor             #DCD090

active_tab_foreground     #17160E
active_tab_background     #FDF5E4
inactive_tab_foreground   #FDF5E4
inactive_tab_background   #17160E

active_border_color   #FDF5E4
inactive_border_color #17160E
bell_border_color     #806D46

color0      #2B2A24
color1		#806D46
color2		#8C7E24
color3		#8C7E24
color4		#839A6B
color5		#BBA26B
color6		#BBA26B
color7		#F4E9D0
color8		#ABA392
color9		#AB915D
color10		#BBA830
color11		#BBA830
color12		#AECD8F
color13		#FAD78F
color14		#FAD78F
color15		#F4E9D0
